project:
  type: website
  output-dir: docs
  resources: 
    - "cv.pdf"
    - CNAME
  render:
    - "*.qmd"
    - "!pols-209/files/"  # dir has .Rmd (-> .pdf) files that should be re-compiled.
    - "!papers2/"

website:
  title: "Carlisle Rainey"
  site-url: https://www.carlislerainey.com
  google-analytics: "G-F57WQLHH67"
  twitter-card: 
    creator: "@carlislerainey"
    image: profile.png
  open-graph: true
  navbar:
    #right:
    tools:    
      - icon: rss
        href: blog/index.xml
        #text: Blog RSS
      - icon: twitter
        href: https://twitter.com/carlislerainey
      - icon: mastodon
        href: https://sciences.social/@CarlisleRainey
      - icon: github
        href: https://github.com/carlislerainey

    left:
      - href: index.qmd
        text: About
      #- href: papers/index.qmd
      #  text: Papers
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching  
      - href: talks/index.qmd
        text: Talks
      - href: blog/index.qmd
        text: Blog
      - icon: rocket-takeoff
        href: email-list/index.qmd
        text: "Get Updates!"
        
  #margin-header: subscribe.html
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

